export const PROGRAM_DETAIL_REQUEST = 'PROGRAM_DETAIL_REQUEST'
export const PROGRAM_DETAIL_SUCCESS = 'PROGRAM_DETAIL_SUCCESS'
export const PROGRAM_DETAIL_FAIL = 'PROGRAM_DETAIL_FAIL'


export const LEVEL_LIST_REQUEST = 'LEVEL_LIST_REQUEST'
export const LEVEL_LIST_SUCCESS = 'LEVEL_LIST_SUCCESS'
export const LEVEL_LIST_FAIL = 'LEVEL_LIST_FAIL'

export const PROGRAM_LIST_REQUEST = 'PROGRAM_LIST_REQUEST'
export const PROGRAM_LIST_SUCCESS = 'PROGRAM_LIST_SUCCESS'
export const PROGRAM_LIST_FAIL = 'PROGRAM_LIST_FAIL'


export const LEVEL_DELETE_REQUEST = 'LEVEL_DELETE_REQUEST'
export const LEVEL_DELETE_SUCCESS = 'LEVEL_DELETE_SUCCESS'
export const LEVEL_DELETE_FAIL = 'LEVEL_DELETE_FAIL'


