export const PROGRAM_DETAIL_REQUEST = 'PROGRAM_DETAIL_REQUEST'
export const PROGRAM_DETAIL_SUCCESS = 'PROGRAM_DETAIL_SUCCESS'
export const PROGRAM_DETAIL_FAIL = 'PROGRAM_DETAIL_FAIL'


export const LEVEL_LIST_REQUEST = 'LEVEL_LIST_REQUEST'
export const LEVEL_LIST_SUCCESS = 'LEVEL_LIST_SUCCESS'
export const LEVEL_LIST_FAIL = 'LEVEL_LIST_FAIL'



export const PROGRAM_LIST_REQUEST = 'PROGRAM_LIST_REQUEST'
export const PROGRAM_LIST_SUCCESS = 'PROGRAM_LIST_SUCCESS'
export const PROGRAM_LIST_FAIL = 'PROGRAM_LIST_FAIL'
export const PROGRAM_LIST_RESET = 'PROGRAM_LIST_RESET'

export const LEVEL_UPDATE_REQUEST = 'LEVEL_UPDATE_REQUEST'
export const LEVEL_UPDATE_SUCCESS = 'LEVEL_UPDATE_SUCCESS'
export const LEVEL_UPDATE_FAIL = 'LEVEL_UPDATE_FAIL'
export const LEVEL_UPDATE_RESET = 'LEVEL_UPDATE_RESET'


export const PROGRAM_UPDATE_REQUEST = 'PROGRAM_UPDATE_REQUEST'
export const PROGRAM_UPDATE_SUCCESS = 'PROGRAM_UPDATE_SUCCESS'
export const PROGRAM_UPDATE_FAIL = 'PROGRAM_UPDATE_FAIL'
export const PROGRAM_UPDATE_RESET = 'PROGRAM_UPDATE_RESET'


export const PROGRAM_CREATE_REVIEW_REQUEST = 'PROGRAM_CREATE_REVIEW_REQUEST'
export const PROGRAM_CREATE_REVIEW_SUCCESS = 'PROGRAM_CREATE_REVIEW_SUCCESS'
export const PROGRAM_CREATE_REVIEW_FAIL = 'PROGRAM_CREATE_REVIEW_FAIL'
export const PROGRAM_CREATE_REVIEW_RESET = 'PROGRAM_CREATE_REVIEW_RESET'


export const LEVEL_CREATE_REQUEST = 'LEVEL_CREATE_REQUEST'
export const LEVEL_CREATE_SUCCESS = 'LEVEL_CREATE_SUCCESS'
export const LEVEL_CREATE_FAIL = 'LEVEL_CREATE_FAIL'
export const LEVEL_CREATE_RESET = 'LEVEL_CREATE_RESET'

export const PROGRAM_CREATE_REQUEST = 'PROGRAM_CREATE_REQUEST'
export const PROGRAM_CREATE_SUCCESS = 'PROGRAM_CREATE_SUCCESS'
export const PROGRAM_CREATE_FAIL = 'PROGRAM_CREATE_FAIL'
export const PROGRAM_CREATE_RESET = 'PROGRAM_CREATE_RESET'


export const LEVEL_DELETE_REQUEST = 'LEVEL_DELETE_REQUEST'
export const LEVEL_DELETE_SUCCESS = 'LEVEL_DELETE_SUCCESS'
export const LEVEL_DELETE_FAIL = 'LEVEL_DELETE_FAIL'

export const PROGRAM_DELETE_REQUEST = 'PROGRAM_DELETE_REQUEST'
export const PROGRAM_DELETE_SUCCESS = 'PROGRAM_DELETE_SUCCESS'
export const PROGRAM_DELETE_FAIL = 'PROGRAM_DELETE_FAIL'

